"""Regenerate authored tyre family/width physical definitions and card metadata."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
# Reproducible fictional tyre family fits; all calculations live in this tool,
# so no external physics library file is edited.
manifest_path=root/'game/assets/components/tyres/catalog.json'
manifest=json.loads(manifest_path.read_text())
families={'road':(1.0,1.0,1.0,500),'track':(1.10,1.10,1.10,500),'slick':(1.20,1.20,1.15,450),'drag':(1.25,.80,1.35,350)}
bases=[('hyper_front',root/'external/physics_sim/data/tyres/hyper_front_265_35r20.json',range(235,396,10),'R20'),('hyper_rear',root/'external/physics_sim/data/tyres/hyper_rear_325_30r21.json',range(235,396,10),'R21'),('passenger',root/'external/physics_sim/data/tyres/passenger_car_225_45r17.json',range(195,356,10),'R17')]
for prefix,path,widths,rim in bases:
    stock=json.loads(path.read_text())
    for family,(gx,gy,rr,rating) in families.items():
        for mm in widths:
            variant=json.loads(json.dumps(stock))
            ratio=mm/(stock['width']*1000)
            key=f'{prefix}_{family}_w{mm}_{rim.lower()}'
            variant['name']=key
            variant['width']=mm/1000
            variant['lambda_mux']=stock.get('lambda_mux',1)*gx*ratio**.35
            variant['lambda_muy']=stock.get('lambda_muy',1)*gy*ratio**.35
            variant['rolling_resistance']['crr_base']=stock['rolling_resistance']['crr_base']*rr*ratio**.65
            variant['rolling_resistance']['rated_speed_kmh']=rating if prefix.startswith('hyper') else min(rating,270)
            variant['source']='Authored racing_game tyre family/width fit, not measured tyre data. Fixed compatible unloaded/rim radii. Grip scales (width/reference_width)^0.35 with family longitudinal/lateral factors; rolling resistance base scales width^0.65 with family factor; rating is authored intended speed regime, not failure model. Generated by tools/generate_tyre_variants.py. Reference '+path.name
            (root/'data/tyres'/f'{key}.json').write_text(json.dumps(variant,indent=2)+'\n',encoding='utf-8')
            aspect=round((stock['unloaded_radius']-stock['rim_radius'])*100000/mm)
            manifest['parts'][key]={'label':{'road':'Performance road','track':'Track semi-slick','slick':'Racing slick','drag':'Drag'}[family],'family':family,'width_mm':mm,'size':f'{mm}/{aspect} {rim}', 'image':f'res://assets/components/tyres/{family}.png','rated_speed_kmh':variant['rolling_resistance']['rated_speed_kmh']}
for key,part in manifest['parts'].items():
    part.setdefault('family','track' if 'track' in key else 'road')
    part.setdefault('width_mm',int(part['size'].split('/')[0]))
manifest_path.write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
print('Tyre definitions and card entries generated:',len(manifest['parts']))
